### ISSUE TITLE
Subdomain reports generate: Failed to add an incoming report: unknown domain

### ISSUE THREAD

**Issue by reingit** [liuch/dmarc-srg#10]
When subdomains have different policies, or at least generate their own reports. Things stop working.
Any (easy) fix for this? Can I manually add the subdomains in the DB?

        try {
            $fqdn = $this->data['domain'];
            $domain = new Domain($fqdn);
            if (!$domain->exists()) {
                // The domain is not found.
                // It will automatically added a new domain if there are no domains in the table
                // or will throw an error otherwise.
                if (DomainList::count() !== 0) {
                    throw new Exception('Failed to add an incoming report: unknown domain', -1);
                }

Is what errors out.

**Comment by liuch** [comment]
Hi, reingit! The DB has a table named `domains`, that stores allowed domains, so you can add new records to it. You can also add any domain to the DB via the web interface (Main menu --> Settings --> Domains). I hope this helps you.

**Comment by liuch** [comment]
I would like to clarify: only the first domain from the first processed report will be automatically added to the database. The rest of the domains must be added explicitly.

**Comment by reingit** [comment]
Thank you for your quick response. Indeed adding from the interface works.
What is the reasoning for only adding the first one? Maybe to prevent "spammers" filling up the database with domains by just sending dmarc rua's?
Since I have hundreds of subdomains (that come and go) with possibly different dmarc policies, do you think it would work to do auto creation based on a regex or the fqdn? As in to allow it to automatically create subdomains as long as the main domain is already there?

You think something like this *untested* could work:
            $fqdn = $this->data['domain'];
            $domain = new Domain($fqdn);
            if (!$domain->exists()) {
                // The domain is not found.
                // It will automatically added a new domain if there are no domains in the table
                // or will throw an error otherwise.
                if (DomainList::count() !== 0) {
					// Check if this is for a subdomain and the "main" domain exists in the DB.
					if (preg_match('/[a-z0-9][a-z0-9\-]{0,63}\.[a-z]{2,6}(\.[a-z]{1,2})?$/i', $fqdn, $match)) {
						if ($match[0]->exists()) {
							// Allow creation of subdomains automagically when root/main domain already exists...
					    } else { throw new Exception('Failed to add an incoming report: unknown subdomain', -1); }
					} else {
						throw new Exception('Failed to add an incoming report: unknown domain', -1);
					}
                }

                $domain = new Domain([
                    'fqdn'        => $fqdn,
                    'active'      => true,
                    'description' => 'The domain was added automatically.'
                ]);
                $domain->save();
            } elseif (!$domain->active()) {
                throw new Exception('Failed to add an incoming report: the domain is inactive', -1);
            }

**Comment by reingit** [comment]
I assume you filter out these domains since you don't want spammers to fill up the DB with sending rua support for other domains?
Since I'm in the situation where I have 100+ subdomains with (possible) different dmarc policies that come and go I'm not sure if adding by hand will work.

What if I do something like this: (untested), you think that could work:
`
$fqdn = $this->data['domain'];
$domain = new Domain($fqdn);
if (!$domain->exists()) {
	// The domain is not found.
	// It will automatically added a new domain if there are no domains in the table
	// or will throw an error otherwise.
	if (DomainList::count() !== 0) {
		// Check if this is for a subdomain and the "main" domain exists in the DB.
		if (preg_match('/[a-z0-9][a-z0-9\-]{0,63}\.[a-z]{2,6}(\.[a-z]{1,2})?$/i', $fqdn, $match)) {
			if ($match[0]->exists()) {
				// Allow creation of subdomains automagically when root/main domain already exists...
			} else { throw new Exception('Failed to add an incoming report: unknown subdomain', -1); }
		} else {
			throw new Exception('Failed to add an incoming report: unknown domain', -1);
		}
	}

	$domain = new Domain([
		'fqdn'        => $fqdn,
		'active'      => true,
		'description' => 'The domain was added automatically.'
	]);
	$domain->save();
} elseif (!$domain->active()) {
	throw new Exception('Failed to add an incoming report: the domain is inactive', -1);
}
`

**Comment by reingit** [comment]
obviously I can't make codeblocks on github. sorry for that. also the regex is just something i grabbed from google for now ..
It's more that i'm wondering if you see a problem with hacking something in there at ./classes/Report/Report.php or  that you see it breaking other stuff.

Thanks so far!

**Comment by liuch** [comment]
> I assume you filter out these domains since you don't want spammers to fill up the DB with sending rua support for other domains?

Yes, you are right. This is exactly what my idea is. Moreover it is necessary for a quick selection of reports for the specified domain from the DB.

> What if I do something like this: (untested), you think that could work:

This will definitely not work out, because the table where reports are stored has a field `domain_id` and each report  must match a record in the `domains` table.

I wrote this for my own little mail server which has fewer requirements than yours. I see the only way out in the form of support for wildcard domain in my project, something like `*.yourdomain.net`. But then you will only get one summary report for such a wildcard domain, no subdomain breakdown. **This feature is currently not implemented.** Maybe it is better to use another project according to your requirements?

**Comment by liuch** [comment]
One more way is to add an option for automatically adding any new domains (not only the first one) in the DB, but then there will be a problem with cleaning unused domains.

**Comment by llsnndlldkm** [comment]
Could you make this an option (conf + web interface) so people can decide for themselves if they would like to have domains added automatically?

**Comment by liuch** [comment]
Yes, I think that's a good idea. I will add this option soon.

**Comment by reingit** [comment]
Thank you! Just tested this and can confirm it works.
