### ISSUE TITLE
Show DMARC disposition on Report List

### ISSUE THREAD

**Issue by KlaasBonnema** [liuch/dmarc-srg#100]
The report list shows the DKIM and SPF status in the result column and in the header status.

Please note that this is the alignment status, not the DKIM or SFP evaluation result.
The mail server will first evaluate SPF authentication - is the mail server allowed to process mail on behalf of the Mail From domain (aka: envelope address, Return-path: header). This will give an SPF result: pass, fail, tempfail,...  
Then the mail server will compare the Mail From domain with the From: header. An SFP pass result and a matching domain will give an SFP align pass.
DKIM is similar but alignment is testing the DKIM-Signature: domain with the From: header and there can be multiple DKIM-Signatures, One DKIM-Signature: with a pass result and matching domain is enough to give a DKIM align pass.

If there is one of SPF align pass and DKIM align pass then the DMARC disposition will be none. If there is no SPF or DKIM align pass then the DMARC disposition can be none, quarantine or reject based on the published DMARC policy.

However the mail server may apply other (local) policies that will return a disposition none, even if there is no alignment and a quarantine or reject policy. This may happen for example if the mail server detects that the mail was forwarded and it trusts the forwarding mail server evidence (ARC-SEAL, SRS or other.) 

The request is to add a DMARC disposition item to the result column. Add the number of not aligned e-mails to the disposition item if not 0 and add the disposition status (quarantine, reject) if not equal to none. This way it is easy to see the actual disposition of the reported mails and the difference between not aligned and quarantined or rejected.

Also add a DMARC quarantine and a DMARC reject item to the top status line in addition to not aligned. Hide the entriy if the count is zero.

Add DMARC disposition to the report filter conditions.

**Comment by liuch** [comment]
Almost everything is implemented
