### ISSUE TITLE
Enhance information on the Summary Reports page

### ISSUE THREAD

**Issue by KlaasBonnema** [liuch/dmarc-srg#102]
The Summary Reports page gives a valuable overview of mail status by sending mail server and by reporting organisations.
The information on actual disposition is however not fully included.

The request is to add to the Summary section: the counts for disposition quarantine and reject. These are not same as the count of not aligned.

Add disposition count/% to the server list: none, quarantine, reject and not aligned.

Add SPF, DKIM aligned, partial aligned, not aligned, quarantine, reject to the reporting organisations section.

Rename "Organisations" to "Reporting organisations".

**Comment by liuch** [comment]
Implemented with this commit: eb8732992d10baef142171a07e6c45a388df9944
