### ISSUE TITLE
error "ACL not available on this IMAP server"

### ISSUE THREAD

**Issue by Havbaba** [liuch/dmarc-srg#104]
I filled in the conf.php file and set up the database, there should be 8 unread mails in the mailbox.
Anyway I don't see any mails showing up and when running the check_config.php I get following output:
https://ibb.co/B3dRBND

`dmarc-srg [error]: imap_getacl: ACL not available on this IMAP server`

- What does this mean and how do I solve this?

Also in the conf.php file:
```
$mailboxes = [
    // Just for displaying in the web-admin and utilities. Not necessary.
    'name'            => 'Dmarc-Rua',
    // Host of the email server. You can specify a port separated by a colon.
    'host'            => 'localhost',
    // Connection encryption method. The valid values are:
    // 'none'     - without encryption (strongly not recommend).
    // 'ssl'      - SSL/TLS on a separate port, for IMAP it is usually port 993. Default value.
    // 'starttls' - STARTTLS method, usually on the standard IMAP port 143.
    'encryption'      => 'ssl',
    // Set true if you want to connect to the IMAP server without certificate validation
    'novalidate-cert' => true,
    // Mailbox user name.
    'username'        => '*hidden*',
    // Mailbox password.
    'password'        => '*hidden*',
    // Mailbox name
    'mailbox'         => 'INBOX',
    // IMAP authorization methods to be excluded.
    // For example: 'auth_exclude' => [ 'GSSAPI', 'NTLM' ]
    'auth_exclude'    => []
];
```
- I am not sure what to add for host?

**Comment by liuch** [comment]
Hello @Havbaba,
Try using `'auth_exclude' => [ 'GSSAPI' ]` in your conf.php

**Comment by liuch** [comment]
Does your email server have Access Control List (ACL) Extension?

**Comment by liuch** [comment]
> What does this mean and how do I solve this?

I did a little investigating. I believe you don't have an ACL configured on your mail server, and it's not an error but a warning that should have gone into the log. The utility will work just as well.

**Comment by Havbaba** [comment]
I am not aware of such thing, so indeed I guess it isn't configured.
I am using a reseller shared hosting @Combell

Anyway at the Logs tab I don't see any logs and the Report List is also empty even there are 8 unread mails with dmarc info.
Both tabs show "No data"

**Comment by liuch** [comment]
Hm. Reports that are in the mailbox will not download themselves. You need to either download them yourself or set up a cron job to do so. Use utils/fetch_reports.php for that.

**Comment by Havbaba** [comment]
Aha okay I get it, works after running the fetch script!
Thanks! :)
