### ISSUE TITLE
kerberos error

### ISSUE THREAD

**Issue by shushulin76** [liuch/dmarc-srg#106]
Hi i get this message on ms exchange server 2016, account is ok because i can logon with it from the same network.

PHP Notice:  Unknown: Kerberos error: No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_0) (try running kinit) for mail.example.com (errflg=1) in Unknown on line 0

**Comment by liuch** [comment]
Try the instructions from this comment: https://github.com/liuch/dmarc-srg/issues/65#issuecomment-1544945603

**Comment by liuch** [comment]
Is this issue relevant?
