### ISSUE TITLE
Feature Request - Reporting for multiple domains at once

### ISSUE THREAD

**Issue by andrewhenke** [liuch/dmarc-srg#109]
Hello! 

Would it be possible to add the ability to select multiple domain names to be used in a single report? This would be greatly helpful for generating holistic reports for clients that have multiple domain names under my DMARC management and monitoring. 

Thank you!

**Comment by liuch** [comment]
From the comments in utils/summary_report.php:

> The `domain` parameter must contain a domain name, a comma-separated list of domains, or `all`.

Did you mean something else?

**Comment by andrewhenke** [comment]
Yes, I mean when using the UI of the web interface, the ability to select multiple domains -- my apologies for the confusion!

**Comment by liuch** [comment]
I just added this feature. Could you please text it?

**Comment by andrewhenke** [comment]
Hello! 

It looks like the ability to select multiple domains is working! 

I opened a new issue for it, but please also see #118, which is related to this. 

Thank you!

**Comment by liuch** [comment]
If I understand you correctly, you can simply save the report settings in your browser as bookmarks, since the tab address in the browser address bar is different for different report settings. Additional convenience: grouped bookmarks can be opened all at once.
