### ISSUE TITLE
NP tag causes error to be logged

### ISSUE THREAD

**Issue by BruceMcKinnon** [liuch/dmarc-srg#111]
The "np" (Non-existent Domain Policy tag - RFC 9091) causes an error to be reported.

"np" Non-existent Domain Policy. Specifies how mail from non-existent subdomains is treated. Added in [RFC 9091](https://datatracker.ietf.org/doc/html/rfc9091).

XML fragment from google.com:

```
<policy_published>
    <domain>mydomain.com.au</domain>
    <adkim>r</adkim>
    <aspf>r</aspf>
    <p>none</p>
    <sp>none</sp>
    <pct>100</pct>
    <np>none</np>
  </policy_published>
```

Error logged:

Event time: 15/01/2024, 12:00:04 am
Result: Failed
Domain: n/a
Report Id: n/a
File name: google.com!mydomain.com.au!1705104000!1705190399.zip
Source: email
Message: Unknown tag: NP

(https://datatracker.ietf.org/doc/html/rfc9091).

**Comment by liuch** [comment]
The handling of this tag was added on on Jun 13, 2023. See here for the details: https://github.com/liuch/dmarc-srg/issues/68.

**Comment by BruceMcKinnon** [comment]
Apologies - I didn't correctly upgrade from 1.7 to 1.8, so the error was still being logged. I re-upgraded and it's all working fine now. Thanks for the awesome tool.
