### ISSUE TITLE
Feature Request: Button to manually retreive email

### ISSUE THREAD

**Issue by BruceMcKinnon** [liuch/dmarc-srg#112]
Feature Request: Add a button to allow emails in the dmarc inbox to be retrieved and processed, rather than relying solely on CRON jobs.

**Comment by liuch** [comment]
Do you mean the button in the web interface?

**Comment by BruceMcKinnon** [comment]
Yes. :)

**Comment by andrewhenke** [comment]
+1 on this, would be highly useful for clients to be able to update the latest records on the system without needing my team's involvement each time.

**Comment by liuch** [comment]
I plan to implement this in the near future.

**Comment by liuch** [comment]
Done with https://github.com/liuch/dmarc-srg/commit/c49fbbb98c4901874109d3768f7cf2d22938105f

**Comment by BruceMcKinnon** [comment]
Awesome. Thank you.
