### ISSUE TITLE
utils/fetch_reports.php does not list mailbox messages

### ISSUE THREAD

**Issue by iactiva** [liuch/dmarc-srg#114]
Hello,

I've started using this nice piece of software some days ago. My mailbox actually have 15 dmarc rua messages however running utils/fetch_reports.php seems not to be reading any message.

Here is the script output (php 7.4.33):

dmarc-srg [error]: ErrorException: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /home/dmarc/public_html/classes/Mail/MailMessage.php:111
Stack trace:
#0 /home/dmarc/public_html/init.php(32): {closure}()
#1 /home/dmarc/public_html/init.php(32): require_once()
#2 [internal function]: {closure}()
#3 /home/dmarc/public_html/classes/Mail/MailBox.php(233): spl_autoload_call()
#4 /home/dmarc/public_html/classes/Sources/MailboxSource.php(81): Liuch\DmarcSrg\Mail\MailBox->message()
#5 /home/dmarc/public_html/classes/Report/ReportFetcher.php(113): Liuch\DmarcSrg\Sources\MailboxSource->current()
#6 /home/dmarc/public_html/utils/fetch_reports.php(153): Liuch\DmarcSrg\Report\ReportFetcher->fetch()
#7 {main}
Error: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence (-1)

I can list messages using other php scripts with something like:
`imap_open("{myserver.com:993/imap/ssl/novalidate-cert}INBOX", "dmarc-rua@myserver.com", "mypasswd")`

Of course my config/conf.php include the same options and mailbox details.

Any help would be much appreciated.

Kind regards,

**Comment by liuch** [comment]
Hello,
This issue was fixed three months ago but is not yet included in the latest release. You can try using the master branch.

**Comment by liuch** [comment]
Here is the fix: https://github.com/liuch/dmarc-srg/commit/178fc106ac1458f4cda48edcf580b8addc68a260

**Comment by iactiva** [comment]
I confirm it is solved. 
Thank you so much!
