### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by AlexPBrin** [liuch/dmarc-srg#115]
changed the password and still doesn't work

**Comment by liuch** [comment]
Did you copy the config/conf.sample.php file to config/conf.php? If so, could you show the part of your config file with the lines where you changed the password? Replace your password with something else like ***.

**Comment by AlexPBrin** [comment]
yes it's on config/config.php

![Screenshot 2024-01-18 153638](https://github.com/liuch/dmarc-srg/assets/33441315/4b1eaf3a-8c69-4553-bada-5db855a172c4)
![Screenshot 2024-01-18 1537501](https://github.com/liuch/dmarc-srg/assets/33441315/9a3d90c5-8d9d-420b-b323-f3816d30ea66)

**Comment by AlexPBrin** [comment]
I ran inspect and login.php returns 400 (bad request)

**Comment by liuch** [comment]
What webserver are you using?

**Comment by AlexPBrin** [comment]
https://www.inmotionhosting.com, CPANEL

**Comment by andrewhenke** [comment]
I am also having this issue @liuch . I did some digging and it looks like the default handler in the login.php code is to return a 400 bad request message if the HTTP request type is not an HTTP GET request -- and, of course, the login credentials are sent via HTTP POST. 

https://github.com/liuch/dmarc-srg/blob/41eb96c8f05d8cc4dafdb39df78e806fee512a13/public/index.php#L25-L32

Could this be a cause of this?

**Comment by liuch** [comment]
Nginx, I suppose.
Could you see what type of request the browser is sending and the value of the http header Accept. They must be 'POST' and 'application/json'.

**Comment by andrewhenke** [comment]
@liuch please see the below screenshot, and also note that my server runs Apache with PHP 8.2

<img width="829" alt="Screenshot 2024-01-18 172230" src="https://github.com/liuch/dmarc-srg/assets/24320242/f9181412-078d-4d2f-b724-9c939bf53c25">

**Comment by liuch** [comment]
@andrewhenke What if you exclude the lastest commit? I think it causes the issue. Could you check that?

**Comment by andrewhenke** [comment]
> @andrewhenke What if you exclude the lastest commit? I think it causes the issue. Could you check that?

@liuch I tried that, and it didn't work for me. Could you please reference the commit hash I should revert to, and test with, so I can attempt this and make sure that we are speaking of the same commit?

**Comment by liuch** [comment]
This one: https://github.com/liuch/dmarc-srg/commit/41eb96c8f05d8cc4dafdb39df78e806fee512a13
And could you tell me which version you were using before the problem appeared.

**Comment by andrewhenke** [comment]
Let me give it a try, and I was using the latest version of the code you released for the S3 integration, and it was perfectly fine for weeks. I don't entirely remember if I updated the code or not again after that, but it essentially overnight stopped working, and I don't have automatic git pulls set up for this repository. 

I'll update you in a moment on the status of testing with the referenced commit.

**Comment by liuch** [comment]
Thank you a lot.

**Comment by andrewhenke** [comment]
@liuch  I just tried this commit and it also did not work. Same error.

**Comment by liuch** [comment]
@andrewhenke What is strange. Did I understand you correctly and you are using apache2 as a web server? Thank you again.

**Comment by andrewhenke** [comment]
@liuch  that is correct, I'm using Apache webserver with PHP 8.1. Is there any additional information I can provide for you?

**Comment by liuch** [comment]
That is enough. I'll try to create a similar configuration. Thank you.

**Comment by liuch** [comment]
Fixed with https://github.com/liuch/dmarc-srg/commit/f8ded32c3c0a98741659147db1202ce42ea5f0d5.

**Comment by AlexPBrin** [comment]
TYVM

**Comment by liuch** [comment]
YW
