### ISSUE TITLE
Feature Request -- Export Summary Reports to CSV

### ISSUE THREAD

**Issue by andrewhenke** [liuch/dmarc-srg#118]
Hello! 

Is it possible to add a new view method that allows us to view/download a CSV of the data? When I need to run reports, the 'raw' format is not proper markdown table format, and the data points are not delimited, so I cannot use the raw data directly in a report without having to manually format to CSV and then import to a spreadsheet -- I would **_greatly_** appreciate this functionality, as I use this system with over 40 domain names for numerous clients. 

Thank you!

**Comment by liuch** [comment]
Hello!
When you pick HTML format, in fact the server returns JSON data. Is JSON not suitable for you?  If not, how should the data be presented in it, just line by line without any structure or formatting? It's not so difficult.

**Comment by liuch** [comment]
Done with https://github.com/liuch/dmarc-srg/commit/b91a9ee38810b5f0332f4e2efc2818b84fb78000

**Comment by andrewhenke** [comment]
This looks great, thank you so much! :)

**Comment by liuch** [comment]
You're welcome! I'm closing this then.
