### ISSUE TITLE
admin login setting to assign the domains to user login

### ISSUE THREAD

**Issue by jodhpurlaxman** [liuch/dmarc-srg#119]
Hello,
The admin user don't have option to set domains for the users to see the reports specific to the domain.
The intresting thing is database has userdomains table but admin user has no option to assign to domain to users.
Please provide an option to admin user or user to select/add/remove domain for the specific user or it self.

**Comment by liuch** [comment]
Hello,
I'm planning to add this functionality. You can see more details in this issue: #67
