### ISSUE TITLE
Feature request - Graphs in reports

### ISSUE THREAD

**Issue by SteelPC** [liuch/dmarc-srg#125]
A little graph in the report section would be nice :)

**Comment by liuch** [comment]
Hi @SteelPC, This is on my to-do list. But I'm not sure if it will be implemented any time soon. I am sorry.  It was discussed here: #79

**Comment by SteelPC** [comment]
Didn't see it was already requested ;)

**Comment by liuch** [comment]
> 1.Graphs. This is by far the biggest addition since it gives immediate visual information.

Isn't that what you meant?

**Comment by SteelPC** [comment]
Yes it is. That why I closed this one and marked it as duplicate.
