### ISSUE TITLE
Need install help

### ISSUE THREAD

**Issue by lyonelf** [liuch/dmarc-srg#126]
Hello,

i try to install it in a debian 12

I have installed php and mariaDB

Copied source app in /var/www/dmarc-srg

When i launch  php utils/database_admin.php init
ia have: Message: Error! Database access denied

What i missed?

Thanks

**Comment by liuch** [comment]
https://github.com/liuch/dmarc-srg?tab=readme-ov-file#create-the-database

**Comment by lyonelf** [comment]
yes i did all on this article

**Comment by lyonelf** [comment]
Yep that it. Not the good name in name value

**Comment by lyonelf** [comment]
Other question


how can i manage email reports with microsoft 365, non password shared mailbox and MFA?

**Comment by liuch** [comment]
Receiving incoming reports from the mailbox is only possible with a username and password. I have nothing to test other configurations on. You can try using Server directory or Remote FS for this. Sorry.

**Comment by lyonelf** [comment]
Near the same issue with a gmail account
I set correct credentials:

![image](https://github.com/liuch/dmarc-srg/assets/34097487/75932f8d-ddac-45d6-9733-421aac6338a6)

**Comment by liuch** [comment]
Have you tried logging in yourself with your credentials (without using the tool)?

**Comment by lyonelf** [comment]
Yes i'm logged perfectly via gmail website. imap is activate

i don't think there is some logs available in gmail

**Comment by liuch** [comment]
Perhaps you used the account's primary password? Gmail requires you to generate a separate password for applications (app passwords): https://support.google.com/accounts/answer/185833

**Comment by lyonelf** [comment]
Tried to update in 2.0 but impossible to set correctly the apache conf

i have a blank page if in the sites-enable/ xx.conf i set the document root to /var/www/html/public/

**Comment by liuch** [comment]
May I close this?

**Comment by liuch** [comment]
> Can i suggest you to add a favicon to your site?

It has to be drawn first... I'll reflect on it. Any way, you can throw any favicon you like into the public/ directory and the browser will most likely pick it up without editing the index file.
