### ISSUE TITLE
Feature Request: csv export

### ISSUE THREAD

**Issue by lyonelf** [liuch/dmarc-srg#127]
Hi,

i'd like to suggest this feature, to easily cross with, for example, an export from microsoft 365 mail explorer and find what is no aligned.

**Comment by liuch** [comment]
I have never used Microsoft 365 mail explorer. Could you please clarify what you mean exactly?

**Comment by lyonelf** [comment]
This an interface where you can check email destination, by IP for example .

By comparing IP address i can find the internal service which use an emailing provider that is not correctly recorded

![image](https://github.com/liuch/dmarc-srg/assets/34097487/2e3c0498-56d3-4ce7-ac6c-d95c28801122)

**Comment by liuch** [comment]
I still don't understand what data needs to be exported. From your screenshot I see that it is analyzing email messages. But RUA reports do not contain data of individual messages, only aggregated ones. If you need a IP addresses list, you can get it from summary report in Web UI, in CSV format.

**Comment by lyonelf** [comment]
ok thanks, i think this is enought
