### ISSUE TITLE
Email reports for all domains 

### ISSUE THREAD

**Issue by francoisPE** [liuch/dmarc-srg#13]
Hello,

Now, it works, I would like create a cron job sending a report for each domain, such as:

domains="$(curl https://dmarc.dom.tld/domains.php -u pswd | gawk 'to be defined')" # to capture domains name
for i in domains
do
php utils/summary_report.php domain=$i period=lastmonth
done

My issue is that curl is not working with -u option...
Is there a way to capture domains with `php domains.php` 
This command gives : PHP Fatal error:  Uncaught Error: Call to undefined function Liuch\DmarcSrg\getallheaders()

**Comment by liuch** [comment]
No, there is currently no way to get a list of domains with my tool. This was discussed here: #10. I didn't even imagine that this functionality would be in demand. You can get this list by using something like this:
`mysql -u"<db_user_name>" -p"<db_passw>" -D"<db_name>" -BNe "SELECT fqdn FROM domains WHERE active = 1;"`

But it will be a better idea to improve on of my scripts. I will thing about it.

**Comment by liuch** [comment]
I'm just curious: why don't you want just to add a few cron jobs? Do you have many mail domains?

**Comment by francoisPE** [comment]
That's a nice idea to capture domains from Mariadb. I'll do so !

I don't have so many domains for the time being, but, I try to increase that number and I would like to have a robust process : avoiding to forget to add a cron job when adding a domain !

Many thanks for your time and expertize :-)

**Comment by francoisPE** [comment]
I am back.
I run that script
"
#!/bin/bash
period=$1
path=$2
cd $path/ && /usr/bin/php utils/fetch_reports.php
domains=$(/usr/bin/mysql -u"DBUSERNAME" -p"DBUSER_PSWD" -D"DBNAME" -BNe "SELECT fqdn FROM dmarc_domains WHERE active = 1;")
for i in $domains
do
  cd $path/ && /usr/bin/php utils/summary_report.php domain=$i period=$period
done
cd $path/ && /usr/bin/php utils/mailbox_cleaner.php
"
with that cronjob
0 0 * * 1 /pthtomyscript/send_mails_report.sh lastweek /mypathtowebsite

It works perfectly except that, today Jan the 17th, it gives week -> jan 03 to jan 09
How should I modify my cron to have lastweek -> jan 10 to jan 16 ?

**Comment by liuch** [comment]
Hi francoisPE,
I think you should not run your job exactly at midnight or it's because the local time on your server is not UTC. Any way, you should not run this script next to the end of the week, because some servers send their reports with some delay, that can last several hours and their reports will not be added to the report. It's mine:
`0 11 * * 2 www-data cd /my/path/to/www && php utils/summary_report.php domain=mydomain.net period=lastweek`

Good luck!

**Comment by francoisPE** [comment]
Thanks a lot
I put mine at 7:00.
I am in France. It should be ok
