### ISSUE TITLE
Unknown tag on import of web.de dmarc files

### ISSUE THREAD

**Issue by ReVoLt112** [liuch/dmarc-srg#130]
![Screenshot_20240726-095518](https://github.com/user-attachments/assets/df53c34a-81ae-44d2-b02a-70792862c055)

Maybe some speciality of web.de or new dmarc field

**Comment by liuch** [comment]
Hello!
It seems to be draft edits that didn't make it into the main spec. I found a mention of this field here: https://datatracker.ietf.org/doc/html/draft-ietf-dmarc-aggregate-reporting-13
Since this field is already being used, I'll make sure it's at least ignored.

**Comment by liuch** [comment]
Fixed with db11fc89062ed379df1c8d0a02d96e4f9295d119. Thank you for reporting.
