### ISSUE TITLE
Reporting bug, access to undefined property

### ISSUE THREAD

**Issue by williamdes** [liuch/dmarc-srg#134]
![Screenshot_2024-08-29-23-43-02-853_org mozilla fenix](https://github.com/user-attachments/assets/79e32044-6faa-4957-84c0-9d3b4e21d81d)

v.2.2.1

**Comment by liuch** [comment]
I have not been able to reproduce this problem. I think the problem is either in the browser cache or in the applied patches (the screenshot shows elements that are not in the original code).
