### ISSUE TITLE
Security in `utils/` scripts block requests from `php-cgi`

### ISSUE THREAD

**Issue by ShawnPConroy** [liuch/dmarc-srg#136]
On some servers, `php-cgi` is used rather than `php-cli` for cron jobs, as well as script and command line requests, depending on the configuration.

The lines in PHP scripts in `utils/` block execution based on `php_sapi_name()`. I was able to get cron jobs working by updating the security line from

```
if (php_sapi_name() !== 'cli') {
```
to
```
if (php_sapi_name() !== 'cli' && php_sapi_name() !== 'cgi-fcgi') {
```

**Comment by liuch** [comment]
This block can be safely removed since all scripts related the Web UI have been moved to public/ directory. I'll fix it.
Thank you.

**Comment by liuch** [comment]
Fixed.
