### ISSUE TITLE
Why are all my reports moved to 'failed' folder?

### ISSUE THREAD

**Issue by murraycollingwood** [liuch/dmarc-srg#140]
All my reports are being moved to the 'failed' folder and I don't know why.
The reports are definitely arriving.
They are clearly being processed (as they are turning up in the 'failed' folder).
But there is no mention in the log of any reports being processed.

So, maybe something in my settings.  I'm guessing there are two relevant entries, $mailboxes and $fetcher
```
$mailboxes = [
    'name'            => 'dmarc-all-domains',
    'host'            => 'localhost',
    'encryption'      => 'none',
    'novalidate-cert' => true,
    'username'        => 'dmarc-focus', 
    'password'        => '***********',
    'mailbox'         => 'INBOX',
    'auth_exclude'    => ['GSSAPI', 'NTLM']
];

$fetcher = [
    'mailboxes' => [
        'messages_maximum' => 0,
        'when_done' => 'delete',
        'when_failed' => 'move_to:failed'
    ],
    'directories' => [
        'files_maximum' => 0,
        'when_done'        => 'delete',
        'when_failed'      => 'move_to:failed'
    ],
    'remote_filesystems' => [
        'files_maximum' => 50,
        'when_done'        => 'delete',
        'when_failed'      => 'move_to:failed'
    ],
    'allowed_domains' => ''
];
```

PS the IMAP interface is on the localhost and is only accessible from the localhost, and dmarc-srg is also running from the localhost, so I'm not too concerned with connection security. 

Lastly, I have scheduled the 'fetch_reports' to run once an hour:
`15   * * * *   php /home/dmarc/dmarc-srg/utils/fetch_reports.php
`

In the database tables:
1. the 'domains' table has 4 entries representing the 4 domains I am monitoring, and these are all marked 'active'
2. the 'system' table has an entry for 'version' = '4.0'
3. all of the other tables are empty

I can see in the 'failed' folder dmarc mail from Google for each of these domains.
For example, some headers from one of these 'failed' messages:
```
Date: Thu, 17 Oct 2024 16:59:59 -0700
Message-ID: <720655029830242786@google.com>
Subject: Report domain: focus-computing.com.au Submitter: google.com
 Report-ID: 720655029830242786
From: noreply-dmarc-support@google.com
To: dmarc-focus@sobs.com.au
Content-Type: application/zip; 
	name="google.com!focus-computing.com.au!1729123200!1729209599.zip"
Content-Disposition: attachment; 
	filename="google.com!focus-computing.com.au!1729123200!1729209599.zip"
Content-Transfer-Encoding: base64
X-UID: 3
Status: 
X-Keywords:                                                                       
Content-Length: 937
```

**Comment by liuch** [comment]
- Does the user under whom you run the job have enough privileges for that?
- Are there any errors on the admin->logs page in the web interface?
- Can you try to process these reports via utils/fetch_reports.php and show me the result? You will need to move one or more reports from the failed reports to the inbox and make sure they are marked as unread.

Note that you can load reports via the web interface. If you set debug=1 in the conf.php, you can see more error information in your browser console.

**Comment by liuch** [comment]
Glad to know it all worked out.
