### ISSUE TITLE
Overall summary when generating reports for multiple domains

### ISSUE THREAD

**Issue by ShawnPConroy** [liuch/dmarc-srg#141]
When the summary report tool is used to generate reports for more than one domain, it would be nice to have an overall summary table at the top of the email, as well as a custom subject title. This way, it's easy to skim the top summary of all domains to see if something needs attention in the rest of the email.

The summary for all domains would be a table that lists each domain in its own row. For each domain, it would list the total number of reports for the that domain summed together. That is, volume (emails, reports, reporting orgs), Partial aligned, Not aligned(SPF only, DKIM only), Disposition(quar+rej, fail rate), effectively summarizing the _reporting organization table_ for that domain.

---

Also, rather than the subject title simply listing the number of domains, being able to have a custom label could be useful for those of us with a large volume of domains. Such as "Client X" or "Low Maintenance Domains" or whatever you wish. "DMARC Monthly digest for Low Maintenance Domains"

If no custom subject is given, but a username is given with `domain=all`, use the username.

Though, I'd also like a period of `lastndays:1` to generate the subject line 'daily', similar to the weekly and monthly options. Or, a `lastday` which uses 'daily', if that's easier.

---

Excellent set of scripts. They have been very useful. My requests here get more complicated as it goes on, but also less functional and turn more pleasant user experience focused, if that's a priority.

**Comment by liuch** [comment]
That's a good idea! I will implement it in the near future. Thank you!

**Comment by liuch** [comment]
> If no custom subject is given, but a username is given with domain=all, use the username.

Could you give me an example of a subject line for a user, say Sam?

**Comment by liuch** [comment]
> Though, I'd also like a period of `lastndays:1` to generate the subject line 'daily', similar to the weekly and monthly options. Or, a `lastday` which uses 'daily', if that's easier.

Do I understand correctly that if it will be possible to specify the subject line of the report, this request loses its relevance? I just don't see any other reason to add `lastday` report period if you can set `lastndays:1`.

**Comment by liuch** [comment]
- [x] Custom subject
- [ ] Overall summary table

**Comment by ShawnPConroy** [comment]
> > If no custom subject is given, but a username is given with domain=all, use the username.
> 
> Could you give me an example of a subject line for a user, say Sam?

Rather than "DMARC weekly digest for 4 domains" be "DMARC weekly digest for Sam" because it's ALL of Sam's (or clientABC's) domains. Not critical but you know.


> > Though, I'd also like a period of `lastndays:1` to generate the subject line 'daily', similar to the weekly and monthly options. Or, a `lastday` which uses 'daily', if that's easier.
> 
> Do I understand correctly that if it will be possible to specify the subject line of the report, this request loses its relevance? I just don't see any other reason to add `lastday` report period if you can set `lastndays:1`.

I suppose. For example, I could add the subject parameter "DMARC daily digest for 7 domains". But for people who are doing it quick and dirt for lastndays:1 I just think it would be nice for the subject line to default to daily as the default. But not required, since I'd probably have a different name than daily digest for 7 domains anyway.

**Comment by liuch** [comment]
Done with 1500eb6bacd32ac1e72ee19bf7b5c8e9e87fa1d3 and 25c06154bc121cf048d03f250644761f0a7eaf01. Later I will add a parameter to exclude the overall section from the report for those who finds it is unnecessary.
