### ISSUE TITLE
IMAP not processed?

### ISSUE THREAD

**Issue by OlafV83** [liuch/dmarc-srg#149]
Hi,

The DMARC reports send to the DMARC mailbox aren't loaded, only when I upload the report.
I can see in the maillog that the mails are fetched and the email messages are no longer in the mailbox.

Am I doing something wrong?
Is there a log file somewhere that I can consult?

**Comment by liuch** [comment]
The default settings do not suggest deleting reports from the mailbox. They can be moved to the `failed` subfolder in the same mailbox if such reports had errors. You can see the log file in the web UI.
