### ISSUE TITLE
Undefined constant "Liuch\DmarcSrg\Sources\SORTDATE"

### ISSUE THREAD

**Issue by SAH62** [liuch/dmarc-srg#150]
Thanks for this project! I just installed it and am trying to give it a go. When I try to load reports from a mailbox I get this pop-up error:

Undefined constant "Liuch\DmarcSrg\Sources\SORTDATE"

Any suggestions?

**Comment by liuch** [comment]
Hello @SAH62,
Do you have the php-imap module installed?

**Comment by SAH62** [comment]
Oops, I do now and the issue is gone. Thanks!
