### ISSUE TITLE
FLYFS error

### ISSUE THREAD

**Issue by pjf02536-2** [liuch/dmarc-srg#151]
Failed to get remote filesystem list
  Error message:
    - Required extension is missing: FLYFS.

I cant seem to find it anywhere
Pls advise (and include note in readme)

**Comment by pjf02536-2** [comment]
nm forgot to use source=email ....duh..

**Comment by liuch** [comment]
Hello,
You need to install the flysystem-aws-s3-v3 package. From the conf.sample.php file:

```
/**
 * Type of remote filesystem. Required. Only 's3' is supported at this time.
 * Before using the S3 filesystem, you will need to install the Flysystem S3 package
 * via the Composer package manager or your OS package manager.
 * For the Composer package manager run:
 * composer require league/flysystem-aws-s3-v3
 */
```

**Comment by liuch** [comment]
> nm forgot to use source=email ....duh..

You can simply comment out $remote_filesystems and other unnecessary blocks to avoid specifying a source for retrieving reports.
