### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by fogma** [liuch/dmarc-srg#16]
Hi,

I'm very excited to find this DMARC parsing tool. I just need to get it working :-)

The web interface is working, the database is initialised and the web interface reports the IMAP server is accessible.

Now I'm trying to run _php utils/fetch_reports.php_ from the command line.

Firstly I'm getting a PHP error in utils/MailBoxes.php:
_Parse error: syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in /volume1/web/dmarc-srg/classes/Mail/MailBoxes.php on line 53_

It turns out "list" is a reserved keyword in PHP and cannot be used as a function name. So I renamed this private function to mList and this has improved things (although I've not found if/where "list" it is called yet!)

But then with that "fix" I get another PHP error:
_Parse error: syntax error, unexpected '?' in /volume1/web/dmarc-srg/classes/Mail/MailBox.php on line 61_

I'm wondering why I'm seeing PHP errors, when no one else has reported anything. Do you have any suggestions?
I'm using PHP Version 7.4.9

**Comment by fogma** [comment]
Ahhh.... I'm running PHP 7.4.9 via the web server, but PHP via the command line is version 5.6.11. That will probably explain it!

Let me investigate some more another day......

**Comment by liuch** [comment]
Yes, version 5.6.11 is too old. In fact, I'm surprised it got to line 53 :)

**Comment by fogma** [comment]
@liuch - DmarcSrg is awesome - thank you so much! I've been looking for a PHP DMARC parser for ages and am so glad I came across this. It is now working perfectly :-)
