### ISSUE TITLE
I made a DarkTheme

### ISSUE THREAD

**Issue by kramwell** [liuch/dmarc-srg#18]
Hey, great project this app has so much potential!

I have spent the last few days looking under the hood, some very complex stuff, I am by no means a PHP wizard so there is plenty I don't understand...

I created a DarkTheme anyway, mainly for my poor eyes as looking at this on a white screen at night can certainly sting.

Let me know what you think!

https://github.com/kramwell/dmarc-srg_darktheme

**Comment by liuch** [comment]
Hey kramwell,
Of course, I think it is a good idea to add a dark theme to the project. But now I don't have time for that. Your theme is good, but in my opinion it's too black and the dialogues are too light. I would do this using CSS variables, detecting the browser's theme with [the preferences-color-scheme CSS media query]( https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), and i would use JavaScript to toggle it in as an option. Thanks for your interest in my project!

**Comment by liuch** [comment]
> it would be easier to set the chosen theme in the php config file

Your suggestion would be great if there was a guarantee that only one person uses the web-interface, they like only one theme, and their browser theme is not automatically changed depending on the time of day. I think this option should not be related to a server but a browser.

**Comment by liuch** [comment]
You inspired me to a feat: I have just added a dark theme. So far, only automatic switching is available.

**Comment by kramwell** [comment]
Thats awsome! it looks really nice and clean. I have made a few edits that I think are worthy of a look, and fixed the grey out issue with disabled text (maybe you can see a better way?)

Let me know what you think.

https://github.com/kramwell/dmarc-srg 

You might also notice I swapped the log display order to newest-oldest as reading oldest-to-newest is a pain to have to scroll to the bottom to see the latest log results...

**Comment by liuch** [comment]
> That's awesome! it looks really nice and clean.

Thank you! To be honest, I took the main ideas from one of github dark themes.

> I have made a few edits that I think are worthy of a look

--color-st-txtblue is not like blue at all, more like white;
--color-dg-wait and --color-tt-green look good;
--color-tt-red became less noticeable than before. I'd set it to #f22;

> You might also notice I swapped the log display order to newest-oldest as reading oldest-to-newest is a pain to have to scroll to the bottom to see the latest log results...

Yes, I've noticed your fix. I have slightly different habits and I don't have many entries in my log ((auto cleaning). But I am going to add that to the advanced settings. By the way, have you known you can swap the log display order by clicking on the column title?

**Comment by kramwell** [comment]
> --color-st-txtblue is not like blue at all, more like white;
> --color-tt-red became less noticeable than before. I'd set it to #f22;

The old colour was like a dark purple for me which I think is too dark for the dark-mode, same for the red colour but that seems too bright when switched to dark-mode. Ill poke around Github and see what they might have defined as examples...

> I have slightly different habits

This is great, as I said before I am by no means an expert in this but I do like to tinker alot. So its great that you can take an idea from someone and make it in a way that works for you and the codebase and more importantly contributes overall to the project.

> have you known you can swap the log display order by clicking on the column title?

Yes but it reset every time you refresh. for me I will rarely delete the logs (maybe after 1 year or something) as its certainly valuable info to have in a business setting and to look back on if needed or asked.

Looking forward to the newest revisions!

**Comment by liuch** [comment]
> Yes but it reset every time you refresh.

I added an option to the advanced settings: https://github.com/liuch/dmarc-srg/commit/05412d76250f9d90e9178e8beb65496d379218ec

**Comment by kramwell** [comment]
Love it! the new additions are great and the dark theme is looking really good now and the log order settings is a nice touch!!

I was looking at some new things that could be introduced and would like to hear your thoughts...

-Manually check for new reports, A button you could press to manually check for new reports (instead of wating for the cron job or going into the ssh directly) a button would be useful.

-Custom timestamp, Change timestamp to unix and then let php ini choose the timezone, a setting could then be added to choose which timezone you want to display that updated the php ini, (example- my webserver is in US but im in EU so time is not correct)

**Comment by liuch** [comment]
Thanks for your inspiring words!

> Manually check for new reports

You are right, that would be useful.

> Custom timestamp

My timezone and my server's timezone don't match either. I initially set the time on the server to UTC, incoming reports also come to UTC, it is UTC in the database too (perhaps not everywhere, I should check it out). I generate final reports once a week, so this is never a big problem for me. I will try to do something with the time settings.

Could you specify for which timestamps you would like to have a timezone setting? Why shouldn't it be the browser local timezone? I think it would be better if you create a new issue for that and close this one.

**Comment by kramwell** [comment]
Awesome, I will close this and open new ones with the two things mentioned here.

That is an even better idea to take the browser local time!
