### ISSUE TITLE
Double clicking on a report brings up authentication dialog

### ISSUE THREAD

**Issue by kramwell** [liuch/dmarc-srg#19]
Very interesting bug.

When you click a report and bring up the DMARC Report, if you are on a slower connection (or accessing site via external webserver) and click it twice instead of once it will bring up the report and then the authentication dialog. you can click cancel and it will go away.

Can be easily re-produced by throttling the connection in dev mode on chrome/edge etc. and following above.

![image](https://user-images.githubusercontent.com/43101805/171483388-ba9d65d0-4c3a-4f72-abc1-53654307efed.png)

**Comment by liuch** [comment]
I was able to reproduce this bug. I'll fix it soon. Thank you!

**Comment by kramwell** [comment]
cool, no stress just good to log here!
