### ISSUE TITLE
Logging out with no password set gets you locked out of the app

### ISSUE THREAD

**Issue by kramwell** [liuch/dmarc-srg#20]
Not trying to bug you... (..crickets...)

If you run the setup with the default admin settings in config.php

```
$admin = [
    // Set this value to null or remove this parameter to disable authentication
    'password' => '',
];
```

and then logout of the app, you get locked out

![image](https://user-images.githubusercontent.com/43101805/171490229-9b65144f-479f-4682-abee-fc72bfc1f71b.png)

**Comment by kramwell** [comment]
one option to solve.. is on first run a password can be set that will append settings to config or store in db, that means encryption can be added so its not stored plaintext either, then password change is done through app or can be removed fully in emergencies to reset again? that would tick off a few things and add some nice security...

**Comment by liuch** [comment]
This was done for security reasons: the password with an empty string is always wrong.

**Comment by kramwell** [comment]
I agree, but most people might not set a password and on first run they can access the webpage without changing anything. then if they logout for whatever reason they cant login again... so its a bug.

**Comment by kramwell** [comment]
I've re-tested and its actually due to changing the password when logged in to blank and logging out so expected behaviour my apologies, I'm putting your program through some interesting tasks, and not really real-world scenario anyways. 

I still think its worth looking at not having plain text though (maybe set a default password to 1234) and document in readme as its not obvious...

Thanks for creating this tool!

**Comment by liuch** [comment]
> I still think its worth looking at not having plain text though (and maybe set a default password to 1234) and document in readme as its not obvious...

A hard-coded default password is a bad idea. It's the first thing a hacker checks, and a blank password is rejected not only on the server, but the web interface also explicitly rejects it. How exactly to disable the password is indicated in the comment.

**Comment by liuch** [comment]
Done: https://github.com/liuch/dmarc-srg/commit/84e2196e6734aa386ad93d2b10b5dca2f8e0090d
