### ISSUE TITLE
Manually check for 'new dmarc reports' button

### ISSUE THREAD

**Issue by kramwell** [liuch/dmarc-srg#21]
A button in the web app to manually check for new reports.

Save going in to the backend to run via manual cron or SSH.

Somewhere easy to access (maybe on the side menu?)

**Comment by liuch** [comment]
Could you look at this commit: https://github.com/liuch/dmarc-srg/commit/b49aa5ceae7d1285c1f2f3906b32eea152d515ed? Does it solve this issue?

**Comment by liuch** [comment]
I think that due to the recent updates this issue is no longer relevant. Reopen it if I'm wrong.
