### ISSUE TITLE
Local timezone setting (not server side)

### ISSUE THREAD

**Issue by kramwell** [liuch/dmarc-srg#22]
As discussed, I think it would be great to have the time setting set local and not server side, this would help with reading reports and a better 'out of the box' experience with the average user.

You mentioned using browser local which I think is a fantastic idea!

**Comment by liuch** [comment]
I improved the date handling with [this commit](https://github.com/liuch/dmarc-srg/commit/e3afee200c27644931de13ab338eafe09c9344cf). Even though I haven't added the setting yet, you might find this change useful.

**Comment by kramwell** [comment]
wow, you've put some time into that, looks so neatly done. no issues in testing either. runs fine.

Amazing progress!
