### ISSUE TITLE
Reports show error after time-zone update

### ISSUE THREAD

**Issue by mayall** [liuch/dmarc-srg#23]
The reports are no longer listed but instead show: null is not an object (evaluating 'd1.toISOString')

As an aside, thank you so much for creating this tool! It is really fantastic.

**Comment by liuch** [comment]
Hello, mayall, Unfortunately, I couldn't reproduce this error.

- Is it possible that one of your reports has an incorrect date?
- Could you tell me the line number where the error occurred?

**Comment by liuch** [comment]
I looked into that part of code. I cannot understand how it happens. Perhaps, another error had happened before this one. Can you show me what your browser console says?

**Comment by liuch** [comment]
Hm, Now I'm almost sure that you have incorrectly updated this tool. It looks like if you haven't updated *.js files.
