### ISSUE TITLE
How can I auto create domain name by upload?

### ISSUE THREAD

**Issue by glio** [liuch/dmarc-srg#24]
I try to upload report via .zip file with new domain name, but how can I set it to auto create a new domain name without I need to create it first? because when I setting this dmarc system, I will not open for all , just me, but if I need to create new domain one by one, and it not user friendly.

thanks

**Comment by liuch** [comment]
Hello glio. Have you seen the `allowed_domains` option? You can find a description and some examples in the conf.sample.php file. I think it will help you. You should specify `+.` value there if you want accept reports for all domain, but I would use a stricter rule.

**Comment by glio** [comment]
> Hello glio. Have you seen the `allowed_domains` option? You can find a description and some examples in the conf.sample.php file. I think it will help you. You should specify `+.` value there if you want accept reports for all domain, but I would use a stricter rule.

Thanks, this help a lot, thank you so much

**Comment by liuch** [comment]
Sorry, I made a mistake with the `+.` rule, use `.+` instead. I have edited my post above.

**Comment by glio** [comment]
> .+

Thank you so much, I just tested, with value ".+" it worked now, thank you
