### ISSUE TITLE
d1 is null

### ISSUE THREAD

**Issue by rafaelmr2** [liuch/dmarc-srg#28]
Hi,

After update (via git pull) I'm gotting the error "d1 is null" in Reports list. It seems to fetch mails OK.

Thanks.

**Comment by liuch** [comment]
Hi,
I was unable to reproduce this error. I found all the sections of code with this variable, but I could not figure out how to get the value null in those variables. Maybe you need to reset your browser cache? I have no other ideas. Could you give me more information on where exactly the error occurred? You can found it in your browser console.

**Comment by rafaelmr2** [comment]
It was crazy, today I'm try to see again and I clicked in "About" in menu. When I do this it worked again. I see that the layout menu has changed. I think it was some kind of cache. 

Thanks.
