### ISSUE TITLE
Report per domain to different email address

### ISSUE THREAD

**Issue by nbwpuk** [liuch/dmarc-srg#29]
Firstly, great software. 👍 

I was just wondering is it possible to send the report per domain to different email address.
I was thinking maybe as the current report is triggered:
`php utils/summary_report.php domain=example.com period=lastndays:10`
could this be adapted to 
`php utils/summary_report.php domain=example.com period=lastndays:10 email=user@example.com`

**Comment by liuch** [comment]
It's a great idea. I just added merged your PR. Thank you for your attention to my project.
