### ISSUE TITLE
Filter report entries

### ISSUE THREAD

**Issue by smeinecke** [liuch/dmarc-srg#40]
Right now its only possible to filter the report list by status of SPF + DKIM, but not entries inside of the report itself. 

Additional it would help if there is some kind of "show only failed validation" checkbox to filter all reports + listings to only show invalid entries.

**Comment by liuch** [comment]
I don't quite understand you. Which entries do you mean? Could you give me some examples?

**Comment by smeinecke** [comment]
In "list display settings" I can filter by "DKIM result" and "SPF result":

![grafik](https://user-images.githubusercontent.com/7316652/196558466-0ecd3749-c95d-4507-87cc-9372f4cd1d8d.png)

which changes output of the "Report List", but when I click on a report, so its opened as overlay, all records are listed even if I set a filter prevously.

**Comment by liuch** [comment]
Oh. You want to filter records inside the report you have chosen, did I understand you correctly? But why? Are there many records in your reports?

**Comment by smeinecke** [comment]
![grafik](https://user-images.githubusercontent.com/7316652/196561343-1e25d260-c03e-4abd-a9a8-6ef3255ba497.png)
Uhm.. yes ;) (last count is amount of records inside ONE report)

**Comment by liuch** [comment]
Is it the number of records not messages? It's a lot then. In this case, report records filtering can be useful. But the number of messages doesn't matter here, because they can all be inside one record. Usually I have 3-5 records in google reports.

**Comment by smeinecke** [comment]
You're right, it's the number of messages. But yes, I have just in this report 132 records:
![grafik](https://user-images.githubusercontent.com/7316652/196566273-fda7b76e-6b85-4d8f-a29b-b516085f007a.png)

**Comment by liuch** [comment]
Okay, now I understand your need. I'll think about the best way to do it.

**Comment by liuch** [comment]
Could you take a look at this: https://github.com/liuch/dmarc-srg/commit/812ed8350a3eb5d780aaa7965766d90c28be2f79 ? It is not everything you asked for, but something.

**Comment by liuch** [comment]
Please note that the filter settings are saved until the tab is closed.
