### ISSUE TITLE
Send summary report as HTML

### ISSUE THREAD

**Issue by nbwpuk** [liuch/dmarc-srg#41]
Is it possible to send the summary report via email the same as the HTML report available in the dashboard?

I have had a read through the code and can't see a way to achieve this.

**Comment by liuch** [comment]
At the moment, this functionality is not provided. I myself prefer mail messages in plain text, so I didn't even think about HTML reports via email. But this is possible to implement.

**Comment by liuch** [comment]
Done: https://github.com/liuch/dmarc-srg/commit/8cf68639796f4d614bda64311b3f2bcf073321dc
