### ISSUE TITLE
Support for application/x-gzip

### ISSUE THREAD

**Issue by TendrilIT** [liuch/dmarc-srg#43]
Some records are encoded as 'application/x-gzip' (Amazon Route 53), but they aren't properly opened and processed.

Adding 'application/x-gzip' to the $mime_type array in classes/Mail/MailMessage.php:82 fixes this error when running `utils/fetch_reports.php source=email`:

Failed to get incoming report:
  Error message:
    - Failed to get the list of mailboxes
    **- Incorrect message: Attachment file type is not valid (application/x-gzip)**
  Email message metadata:
    - From: XXXXXXXXXX <XXXXXX@XXXXXX.XXX>
    - Date: Tue, 25 Oct 2022 13:21:44 -0400

but then it fails in 'classes/ReportFile/ReportFile.php':

Failed to get incoming report:
  Error message:
    **- gzopen(): Filename cannot be empty**

I'm unsure where to look next in order to fix this issue.

Thank you for this tool!

**Comment by liuch** [comment]
Hello!
May I ask you a few questions?

1. What is the extension of the report file?
2. Is it a regular gzip file?
3. Have you tried to upload this file via web interface? Did that succeed?

> I'm unsure where to look next in order to fix this issue

It needs to be fixed at least in three places.

**Comment by TendrilIT** [comment]
1. The attachment looks like this:  amazonses.com!XXXXXXX.XXX!1666569600!1666656000.xml.gz  (domain replaced with XXXXXXX.XXX)
2. It appears to be a regular gzip file.  I can unzip it with the `gzip` command
3. I just tried uploading through the web interface and it _was_ successful.  However, I had to create `/var/spool/dmarc-srg/rua` first.  (I had forgotten to create this path when installing)

**Comment by liuch** [comment]
Thank you a lot! I'll fix the code soon.

> However, I had to create /var/spool/dmarc-srg/rua first. (I had forgotten to create this path when installing)

You might to use `Uploading local report files` to load the report file from your local desktop.

**Comment by liuch** [comment]
Fixed: https://github.com/liuch/dmarc-srg/commit/bd1b045b9baa484fbb989bcc008e264dbf5ab187
Could you check it out?

**Comment by TendrilIT** [comment]
Fixed! Thank you very much!

**Comment by liuch** [comment]
That's fine. So I'm closing this issue then.
