### ISSUE TITLE
Feature : all domains in one email or multuple domains

### ISSUE THREAD

**Issue by Shnoulle** [liuch/dmarc-srg#45]
Hi,

I have some domains , and i like to get whole report in one email only.

Maybe add some solution to allow : all domains or a lits of domains ?

`php utils/summary_report.php period=lastmonth` 
Chcek all know domains

`php utils/summary_report.php domain=example.com;example.org period=lastmonth` 
For a lits of domains 

I can create the pull requets (when i have time)

**Comment by liuch** [comment]
Hi, I personally prefer to receive such reports in separate email messages. But I also remember that people have different preferences. So I will try to implement it in the near future. But the domain separator will be not a semicolon - it has a special meaning in the console.

**Comment by Shnoulle** [comment]
I can create a pull request :).

What do you prefer for separator ?
Allow ALL or not ?

**Comment by liuch** [comment]
I'm going to do that myself, but if you want... :) I think a comma is a good separator. As for ALL, something more flexible needs to be done, not just ALL. I'm still thinking.

**Comment by liuch** [comment]
Done: https://github.com/liuch/dmarc-srg/commit/c94f4a7f2c66369942b39622373f426b153ca57f

**Comment by Shnoulle** [comment]
Work great !

test both : comma separated and all !
Great thanks
