### ISSUE TITLE
Failed to get incoming report

### ISSUE THREAD

**Issue by ReVoLt112** [liuch/dmarc-srg#46]
root@h2983452:~# cd /var/www/html && /usr/bin/php utils/fetch_reports.php
Failed to get incoming report:
  Error message:
    - Creation of dynamic property Liuch\DmarcSrg\Mail\MailAttachment::$encoding is deprecated

**Comment by ReVoLt112** [comment]
Info: PHP 8.2.0RC5

**Comment by ReVoLt112** [comment]
Solution was easy:

File: MailAttachment.php

class MailAttachment
{
    private $conn;
    private $filename;
    private $bytes;
    private $number;
    private $mnumber;
    +private $encoding;
    +private $stream;
    +private $mime_type;

**Comment by liuch** [comment]
Thank you for the report. Fixed.
