### ISSUE TITLE
Failed to fetch the status

### ISSUE THREAD

**Issue by playak** [liuch/dmarc-srg#49]
Looks like a DB connection problem.

I edited the config/conf.php file, and double checked on the command line that the DB user has full access to the database, and I configered a dmarc_ prefix, so there shouldn't be conflicts. The directory is also readable/writeable by the scripts. I hardly have experience with PDO, otherwise I'd dig deeper myself before asking here.

Using PHP 7.4.33 on Linux, '--with-pdo-mysql=shared,mysqlnd', Server version: 5.5.65-MariaDB MariaDB Server.

Looks like a brilliant tool, if I can get it to work :) Ideas anyone? 

Cheers,
Jeroen

**Comment by liuch** [comment]
Hello Jeroen, Could you give me a little more information about this? Are you using the latest version of the tool? I would like to see a part of your conf.php with the database connection settings without your credentials, of course. I also need to see the error message when the database connection fails. You need to enable the debug mode in the conf.php file. Just set `$debug = 1;` (replace 0 with 1) in your conf.php and run `php utils/database_admin.php status` in the console. It will try to connect to the database and then display a detailed error message in the console or save it to the log, depending on how your php is configured.

**Comment by playak** [comment]
Wow, I wasn't expecting such a fast answer.

Yes, I downloaded the latest today before I posted my first message here.

But trying to look into that config file, I noticed that stupid me had renamed to to conf..php instead of conf.php . 

Renaming that file helped a lot. Sorry about that and thanks again for all.

**Comment by liuch** [comment]
It's OK. Anything happens. May I close this issue?

**Comment by liuch** [comment]
I'm closing the issue. Reopen it if you have any questions.
