### ISSUE TITLE
Two errors with PHP8.2 (fix included)

### ISSUE THREAD

**Issue by ReVoLt112** [liuch/dmarc-srg#52]
dmarc-srg [error]: ErrorException: Creation of dynamic property Liuch\DmarcSrg\Report\Report::$db is deprecated in /var/www/html/classes/Report/Report.php:36

Solution declare "private db;" in class

dmarc-srg [error]: ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/classes/Database/Mariadb/ReportMapper.php:598

Solution place dollar sign $ inside the curly braces

**Comment by liuch** [comment]
My oversight. Apparently you need to upgrade to version 8.2. to catch such errors. Thank you so much.

**Comment by liuch** [comment]
There are several other such errors:
```bash
$ grep '\${' 2>/dev/null * -r | wc -l
5
```
Thanks again.

**Comment by ReVoLt112** [comment]
you're welcome

Am 20.12.22 um 20:10 schrieb Aleksey Andreev:

**Comment by liuch** [comment]
Fixed with 9ebc3291f6322511177341300a4a91a08b28c6ef
