### ISSUE TITLE
Call to underfined function Liuch\DmarcSrg\Mail\imap_errors()

### ISSUE THREAD

**Issue by OldToys** [liuch/dmarc-srg#58]
Hello,

I am trying to setup the tool. I don't plan to connect it to my mailbox. Instead, I want to upload DMARC reports manually or point it to a directory where my reports are saved. I keep getting this error message every time I refresh the page or try to do anything in the GUI.
`[Sun Mar 26 15:46:04 2023] dmarc-srg [error]: Error: Call to undefined function Liuch\DmarcSrg\Mail\imap_errors() in C:\Users\**********\dmarc-srg\classes\Mail\MailBox.php:307`
![image](https://user-images.githubusercontent.com/25939712/227804027-4e32980f-f5ef-4372-a5ed-127f3b8001fa.png)
Is there something I am missing. Like I mentioned, I don't plan to use the email integration portion of the tool.

Thank you in advance,

**Comment by OldToys** [comment]
Fixed this by commenting out everything in the $mailboxes section in the config.php file.

**Comment by liuch** [comment]
Okay. Thank you for the information. I'll check it out.
