### ISSUE TITLE
Creation of dynamic property - DirectorySource::$path is deprecated

### ISSUE THREAD

**Issue by OldToys** [liuch/dmarc-srg#59]
Running into this issue now.
![image](https://user-images.githubusercontent.com/25939712/227805105-01efb0fc-117f-45ed-a285-6e2d0fcdb73f.png)
I saw the closed cases and it looks like this issue happens with many components of the scripts but none of them mention it happening with DirectorySource::$path. Any thoughts? Would really love to get this tool up and running.

Thank you,

**Comment by liuch** [comment]
What version of php do you have?

**Comment by OldToys** [comment]
The latest version. 8.2.4. Just installed it today. The GUI upload feature is working for now, which is great, but it would be even better to point the tool to a directory and get the reports from there.

**Comment by liuch** [comment]
Oh, I thought I got rid of all the deprecated code. I was wrong. Thank you for the report.

**Comment by liuch** [comment]
Fixed with f68dc63b5355106dccbc9108350a287c4d06145f. Could you check it please?

**Comment by liuch** [comment]
> but it would be even better to point the tool to a directory and get the reports from there

There is such possibility. You can specify one or more directories and load reports from them via cron or Web GUI.

**Comment by OldToys** [comment]
Yes, everything works flawlessly now. Thank you so much for the quick reply/fix.
