### ISSUE TITLE
Kerberos enabled mail server error

### ISSUE THREAD

**Issue by Entrepreneur-AJ** [liuch/dmarc-srg#65]
Our mail server allows GSSAPI, Plain and Login authentication but can't connect.

running the check_config utility I get the following response;

`=== GENERAL INFORMATION ===
  * OS information: Linux 6.2.14-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May  1 00:55:28 UTC 2023 x86_64
  * PHP version:    8.2.5

=== EXTENSIONS ===
  * pdo_mysql...................... Ok
  * xmlreader...................... Ok
  * zip............................ Ok
  * json........................... Ok

=== CONFIG FILE ===
  * Checking if the file exists.... Ok
  * Checking read permission....... Ok
  * Checking write permission...... Ok
  * Checking access by other users. Ok
=== GENERAL INFORMATION ===
  * OS information: Linux 6.2.14-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May  1 00:55:28 UTC 2023 x86_64
  * PHP version:    8.2.5

=== EXTENSIONS ===
  * pdo_mysql...................... Ok
  * xmlreader...................... Ok
  * zip............................ Ok
  * json........................... Ok

=== CONFIG FILE ===
  * Checking if the file exists.... Ok
  * Checking read permission....... Ok
  * Checking write permission...... Ok
  * Checking access by other users. Ok

=== DATABASE ===
  * Accessibility check............ Ok
  * Checking for integrity......... Ok

=== MAILBOXES ===
  * Checking mailboxes config...... Ok
    Message: 1 mailbox found
  * Imap extension................. Ok
    - Dmarc-Rua
      * Accessibility.............. dmarc-srg [error]: IMAP error: GSSAPI mechanism status: No Kerberos credentials available (default cache: KCM:)
dmarc-srg [error]: imap_getacl: ACL not available on this IMAP server
Ok

=== DIRECTORIES ===
  * Checking directories config.... Ok
    Message: No directories found

===
Success!
=== DATABASE ===
  * Accessibility check............ Ok
  * Checking for integrity......... Ok

=== MAILBOXES ===
  * Checking mailboxes config...... Ok
    Message: 1 mailbox found
  * Imap extension................. Ok
    - Dmarc-Rua
      * Accessibility.............. dmarc-srg [error]: IMAP error: GSSAPI mechanism status: No Kerberos credentials available (default cache: KCM:)
dmarc-srg [error]: imap_getacl: ACL not available on this IMAP server
Ok

=== DIRECTORIES ===
  * Checking directories config.... Ok
    Message: No directories found

===
Success!`

**Comment by liuch** [comment]
Hello Entrepreneur-AJ, I just have added a small fix. Can you check it?

**Comment by liuch** [comment]
I'm going to make this solution an option in the conf.php, since someone might be successfully using gssapi on their server for this tool. After your confirmation, there will be another commit.

**Comment by Entrepreneur-AJ** [comment]
Commit seems to have worked, been able to pull the first set of DMARC Reports today, so ready to move on to next commit. Want me to leave this issue open and test your next relevant commit or close it?

**Comment by liuch** [comment]
Yes, if you don't mind.

**Comment by Entrepreneur-AJ** [comment]
No problem will await next commit

**Comment by liuch** [comment]
Done. You need to add a parameter named `auth_exclude` to your `conf.php` file. You can see an example here: https://github.com/liuch/dmarc-srg/blob/master/config/conf.sample.php#L50

Feel free to ask if you have any questions.

**Comment by Entrepreneur-AJ** [comment]
Latest commit pulled will update once next batch of dmarc reports processed.

**Comment by Entrepreneur-AJ** [comment]
All working properly, hard work is apreciated.

**Comment by liuch** [comment]
Thank you for the report. Have a good day.
