### ISSUE TITLE
Unable to get the web pages to work - Apache on Centos 7

### ISSUE THREAD

**Issue by brianread108** [liuch/dmarc-srg#66]
The batch (CLI) programs run fine and the summary email is sent as expected.

However I've so far been unable to get the Apache config correct (using php-fpm). The page shows the title, and the status boxes (populated with ?) and I get a red error box "[-100] Unexpected token ':', ":{"error_c"... is not valid JSON". 

I interprete my problems as being the backend php is not delivering the JSON to the JS front end.

Here is my httpd.conf contents (taken and edited from another working php program/page):

```
Alias /dmarc-srg /opt/dmarc-srg
<Location /dmarc-srg>
    AuthName "dmarc-srg"
    AuthType Basic
    AuthBasicProvider external
    AuthExternal pwauth
    require user admin
</Location>
<Directory /opt/dmarc-srg>
    SSLRequireSSL
    Options -Indexes
    AllowOverride None
    <RequireAll>
          Require ip 127.0.0.1 xxx.xxx.xxx.0/255.255.255.0 
    </RequireAll>   
    AddType application/x-httpd-php .php 
    <FilesMatch .php$>
      SetHandler "proxy:unix:/var/run/php-fpm/php80.sock|fcgi://localhost"
    </FilesMatch>
</Directory>
```
I've not been able to find any error logs that are useful (neither php nor httpd)

**Comment by liuch** [comment]
I think there is some error on the backend, and text of this error is inserted before the json content. You can see the details of this error in the server logs (if configured) or in the browser console, assuming that the error text goes there.

**Comment by brianread108** [comment]
In the browser console, the message is truncated as per what is show on the screen.

Got any idea which server logs it might appear in?

**Comment by liuch** [comment]
- Set $debug = 1; in your conf.php
- Try running utils/check_config.php
- Try using the web interface again and take a look at the browser console. You may need to expand the request you got the error in to see the full error message.

It would nice to see at which stage you got this error (what did you do before and the query string). What exactly does your browser display?

**Comment by brianread108** [comment]
![Screenshot from 2023-05-28 08-35-59](https://github.com/liuch/dmarc-srg/assets/9008937/b6fca780-21a0-4005-9092-6c492abe7e76)

**Comment by brianread108** [comment]
Actually to me it looks as though the GET of the php file from the JS is not resulting in the php being interpreted and the consequent eror handling is obscuring this.

If this is the case then it comes down to my httpd.conf contents. I have copied and edited these from a set which allow phpmyadmin to run on this server, but perhaps the particular way your package uses JS and PHP might need something a bit more specific?

**Comment by liuch** [comment]
I got the same error message when I added a command that adds `:` to stdout at the beginning of my script. I have no idea how this could happen. Perhaps my information will give you a hint.

![the browser console with error message](https://i.imgur.com/9Ki3RCC.png)

**Comment by liuch** [comment]
There is another reason why this error will appear: the presence of an empty line before this this one: `<?php`

![](https://i.imgur.com/F4hW0ju.png)

Check your conf.php file.

**Comment by brianread108** [comment]
Ok, that was the problem - an extra character on the first line of the config file.  My Bad I guess!

However now I get this:

[-1] session_start(): Setting option &quot;cookie_httponly&quot; failed

It is not clear to me whether I need a password for "admin" in the config file.  The Apache config requires authorisation with the system password.

**Comment by liuch** [comment]
What version of PHP are you using? It must be 7.3 or higher. Environment requirements are listed [here](https://github.com/liuch/dmarc-srg#installation-and-configuration).

**Comment by liuch** [comment]
If you don't have any more questions, may I close this?

**Comment by brianread108** [comment]
Sure. Thanks for the help.
