### ISSUE TITLE
Failed Google reports

### ISSUE THREAD

**Issue by fingerprn** [liuch/dmarc-srg#7]
Your script created a folder called "failed" and it's full of Google reports. I'm assuming these are reports that couldn't be parsed. Not all Google reports are moved to the failed folder, but many are. Is there anything that can be done about this. Thanks!

**Comment by erichk4** [comment]
usually these are reports with the same report id -> they are moved to the failed folder..
some related  infos:
[https://dmarc-discuss.dmarc.narkive.com/aqa1AHds/duplicate-reports](url)
[https://www.mail-archive.com/mailop@mailop.org/msg13585.html](url)

**Comment by liuch** [comment]
Yes, @erichk4 is right. Usually these reports have the same report id because google often sends the same messages twice. You can see if this is the case on the logs page (Administration -> Logs).
