### ISSUE TITLE
This report has already been loaded - duplicate report ID but different date range

### ISSUE THREAD

**Issue by schleup** [liuch/dmarc-srg#81]
Hi,

from Google and Mimecast I get reports with duplicate report IDs but different time ranges. All other data are identical due to the fact that my domains are very low volume senders. So it's plausible that I'm sending one mail to the same Google account each day and get three consecutive reports having the same data, only the time range of each record is different. But the report ID of all reports is identical.

When such a report is processed, I get an error "This report has already been loaded" in the logs. Which is logical, assuming the report ID is unique.

I couldn't find any spec for the report ID, about it's format or uniqueness. And I'm not even sure if this would be a problem at these Mail providers or in dmarc-srg.

Due to the fact that even the records data of these 'duplicate' reports are identical I'm not even missing information about policies ignored - just the message count is wrong.

Any idea how to handle this (or if it even should be handled)?

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<feedback>
  <report_metadata>
    <org_name>Mimecast</org_name>
    <email>no-reply@uk-1.mimecastreport.com</email>
    <extra_contact_info>https://community.mimecast.com/s/knowledge</extra_contact_info>
    <report_id>cdba5bb11cc1b597ea78d1da9133348f8743bb517700364184144e6469f5c004</report_id>
    <date_range>
      <begin>1687564800</begin>
      <end>1687651199</end>
    </date_range>
  </report_metadata>`

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<feedback>
  <report_metadata>
    <org_name>Mimecast</org_name>
    <email>no-reply@uk-1.mimecastreport.com</email>
    <extra_contact_info>https://community.mimecast.com/s/knowledge</extra_contact_info>
    <report_id>cdba5bb11cc1b597ea78d1da9133348f8743bb517700364184144e6469f5c004</report_id>
    <date_range>
      <begin>1687824000</begin>
      <end>1687910399</end>
    </date_range>
  </report_metadata>`

**Comment by williamdes** [comment]
I think I also have some duplicated Google dmarc reports. For now they went to Invalid, but maybe they actually have data that can be processed.
If examples are needed I can dig deeper

**Comment by mbsouth** [comment]
The same here with different domains.

**Comment by liuch** [comment]
Hi,
 It's an interesting question! My utility checks that the report_id is unique within the domain. When I wrote the utility, I followed RFC 7489, but now I cannot find the exact answer to this question. This sentence: "The purpose of the Report-ID: portion of the field is to enable the Domain Owner to identify and ignore duplicate reports that might be sent by a Mail Receiver" says nothing about whether the ID must only be unique within the date range specified in the report or not. Perhaps I misunderstood this RFC: https://datatracker.ietf.org/doc/html/rfc7489. Perhaps it makes sense to add begin_time to the index to check for uniqueness.

**Comment by schleup** [comment]
Hi Aleksey,

yes, I think it would make sense to include the date range (at least the <begin> part of it) to the report ID in the DB.

In the mails I received for these reports I quoted above both dates are included in the attachment's file name:

mimecast.org!####.de!1687824000!1687910399!cdba5bb11cc1b597ea78d1da9133348f8743bb517700364184144e6469f5c004.xml
mimecast.org!####.de!1687564800!1687651199!cdba5bb11cc1b597ea78d1da9133348f8743bb517700364184144e6469f5c004.xml

Google only uses the <begin> date:

google.com!####.org!1687305600!1687391999.xml

Thx,

Florian

**Comment by liuch** [comment]
Note: you need to upgrade the database structure for the changes to take effect.

**Comment by schleup** [comment]
thank you! Just checked, the former 'duplicate' records are imported now

**Comment by williamdes** [comment]
Thank you !
264 new reports !
Yahoo, Mimecast, Fastmail and Google. Mostly old reports, but the Mimecast ones are very recent. I bet their implementation does not follow the RFC

**Comment by liuch** [comment]
I have discovered an unfortunate error. If the database structure was not created anew, but was updated to solve this problem, then in this case the uniqueness of reports is not checked at all. I have already prepared a fix. I'll commit it in a little while. It will automatically remove duplicates and recreate the index. So the number of reports in your database may change. I'm sorry.
