### ISSUE TITLE
Multi user setup

### ISSUE THREAD

**Issue by williamdes** [liuch/dmarc-srg#87]
I do not want to host many instances of DmarcSrg. I need to have a way to give a credential to users of domain/domains XYZ so they do not have access to the other ones.

Can we make:
- a multi password config that each of them has a filter for the allowed domains
- a user/password table with domains by user
- a user/password config that each of them has a filter for the allowed domains

What solution would be best ?

**Comment by liuch** [comment]
I think it would be better to have tables `users` and `user_domains` or something. The admin user is configured in the config file, other users is in tables. What do you think about this? By the way: This feature have been mentioned #67.

**Comment by williamdes** [comment]
Duplicate of #67
