### ISSUE TITLE
imap ssl connection is not working

### ISSUE THREAD

**Issue by benpolman** [liuch/dmarc-srg#9]
If you want a ssl connection to an imap server the host entry in config.php of a mailbox 
should be appended with :993

host = imap.yourdoain.com:993

But that is not sufficient, in classes/Mail/Mailbox.php the server string is created to be used in the imap_open call,
in case of a ssl connection it should end with '/ssl'
A simple fix:
        $flags = '';
        if (isset($params['novalidate-cert']) && $params['novalidate-cert'] === true) {
            $flags = '/ssl/novalidate-cert';
        }
        else {
            $flags = '/ssl';
        }
        $this->server = sprintf('{%s/imap%s}', $this->host, $flags);

**Comment by liuch** [comment]
I think with your fix it will be impossible to connect to the server without encryption. I'm going to write another solution. Thanks for pointing this out.

**Comment by benpolman** [comment]
True, I didn't think about that. But a simple check on if the hostname ends with :993 should fix that.

Sent from MailDroid

-----Original Message-----

**Comment by liuch** [comment]
Now you can specify the type of the connection encryption to your email server. See parameter 'encryption' in config/conf.sample.php

**Comment by benpolman** [comment]
Thanks, that is a perfect solution
