### ISSUE TITLE
Reports counter is for the last 30 days by default

### ISSUE THREAD

**Issue by williamdes** [liuch/dmarc-srg#91]
When the Month filter is "any" and a domain is selected it felt wrong to see the count for the last 30 days.
Can you add a setting for it to count all reports or another time period ?

Or add some header to the count block to say it's for the last 30 days, so the user does not need to hover the counts to figure out the counts are for the last 30 days ?

On this screenshot taken from : https://aws.amazon.com/blogs/mt/understanding-aws-lambda-behavior-using-amazon-cloudwatch-logs-insights/
![image](https://github.com/liuch/dmarc-srg/assets/7784660/75aaff8b-bac4-4a7d-bcfc-bbfdc3309b60)

Amazon has a nice selector that shows that the time period is 30 days. Maybe we could have something like that ?

**Comment by liuch** [comment]
> Can you add a setting for it to count all reports or another time period ?

You can change this in the settings, see the `status.emails-for-last-n-days` option.

I realize that the UI is by no means perfect, but I don't have time or ideas for major tweaks, sorry. Maybe a little later.

**Comment by williamdes** [comment]
> I realize that the UI is by no means perfect, but I don't have time or ideas for major tweaks, sorry. Maybe a little later.

okay, what did you think about the Amazon selector UI ?

**Comment by liuch** [comment]
What do you mean? The whole interface you showed in the screenshot? I don't like it. It's too overcomplicated for a simple task. I'm not even sure it can be packaged into a mobile interface. On the other hand, just because I don't like it doesn't mean it's bad. Maybe it's just that my habits are different.

**Comment by williamdes** [comment]
> What do you mean? The whole interface you showed in the screenshot? I don't like it. It's too overcomplicated for a simple task. I'm not even sure it can be packaged into a mobile interface. On the other hand, just because I don't like it doesn't mean it's bad. Maybe it's just that my habits are different.

I only mean about the selector where you see 15min... 1d .. custom

**Comment by liuch** [comment]
It's too long. I don't see where it can be placed. How often do you use this option? Is it worth placing on the report list page?

**Comment by williamdes** [comment]
> It's too long. I don't see where it can be placed. How often do you use this option? Is it worth placing on the report list page?

You could add the same style of control just above or below the boxes. Not larger than the boxes. It would allow the user to change the filtered time for the statistic

**Comment by williamdes** [comment]
I am not sure was was to be done
