### ISSUE TITLE
Report list changes on refresh

### ISSUE THREAD

**Issue by SteelPC** [liuch/dmarc-srg#93]
Hello, every time I refresh the report list page the listing changes showing different records. Anybody faces the same thing ?

**Comment by liuch** [comment]
Hello, try changing the `status.emails-filter-when-list-filtered` option in the advanced settings. Also, the last commit removed duplicates in incoming reports, but this is a one-time change.

**Comment by SteelPC** [comment]
Updated to last commit, upgraded database, tried to set status.emails-filter-when-list-filtered to "no" but same behavior remains

**Comment by liuch** [comment]
I don't see how that's possible. Could you please give me some details? Any screenshots?

**Comment by SteelPC** [comment]
![intial](https://github.com/liuch/dmarc-srg/assets/71431903/c19bdca1-5311-4fd2-be81-0d8214b01825)
![refresh_1](https://github.com/liuch/dmarc-srg/assets/71431903/9fe5c0f1-634e-4400-a924-7f8be5ee66ee)
![refresh_2](https://github.com/liuch/dmarc-srg/assets/71431903/6568123b-f9fd-4c6d-8033-e7538d8b2f53)
![refresh_4](https://github.com/liuch/dmarc-srg/assets/71431903/318f4a19-13e2-4eb0-ab4b-07854f573505)
![refresh_5](https://github.com/liuch/dmarc-srg/assets/71431903/c945f99c-8fee-4cdc-9a60-6c902915537f)

Screenshots attached I took the domains out but from the reports id you can see the changes.

**Comment by liuch** [comment]
How many domains do you have? I don't need an exact number. Less than ten? More than ten?

**Comment by SteelPC** [comment]
More than 10. 29 to be exact.

**Comment by liuch** [comment]
I think I figured out what the problem might be. Thanks.

**Comment by liuch** [comment]
Could you please check the latest fix?

**Comment by SteelPC** [comment]
Fixed thank you :D

**Comment by liuch** [comment]
Thank you for the report.
