### ISSUE TITLE
Please ignore google' <np> tag

### ISSUE THREAD

**Issue by garyakimoto** [liuch/dmarc-srg#98]
I find google has been added <np>none</np> or  <np>reject</np> in to their dmac report, but dmarc-srg will get error because this tag and not working anymore. please ignore tag for fix this problem, thanks

**Comment by liuch** [comment]
The handling of this tag was added on 13 June. See here for the details: https://github.com/liuch/dmarc-srg/issues/68. Maybe you mean something else?

**Comment by garyakimoto** [comment]
Thank you, so I think I need to upgrade my one
